# Enable full mouse support (clicking, scrolling, pane resizing, and window selection)
# Replaces deprecated options used in tmux versions prior to 2.1
set -g mouse on

# Enable Vi keys in copy mode
set-window-option -g mode-keys vi

# Use 'v' to start visual selection
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Prevent mouse release from exiting copy mode immediately
unbind -T copy-mode-vi MouseDragEnd1Pane

# Cross-platform clipboard support (macOS vs Linux)
if-shell 'test "$(uname)" = "Darwin"' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"'

if-shell 'command -v xclip >/dev/null 2>&1' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"'

# Set background green and text black
set -g status-style "bg=green,fg=black"
set -g status-interval 1
set -g status-right-length 100

set -g status-right "#[fg=black,bg=cyan]  #{b:pane_current_path} #[fg=black,bg=magenta] 󰘬 #(git -C #{pane_current_path} branch --show-current 2>/dev/null | awk 'BEGIN{b=\"--\"} NF{b=\$0} END{print b}') "
